# Site settings
title: Your awesome title
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://awesomeinc.org" # the base hostname & protocol for your site
keywords: "Coding, Coworking, Entrepreneur, Software"

# Markdown settings
markdown: kramdown

# Sass settings
sass:
  add_charset: true
  sass_dir: assets/sass
  style: :compressed
  sourcemap: :true

# Build settings
exclude:
  - package.json
  - README.md
  - CNAME
  # - assets/sass

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-assets
  - jekyll-redirect-from
  - jekyll-sitemap

assets:
  digest: false

collections:
  applications:
    title: Applications
    output: true
    permalink: /:name/apply
  courses:
    title: Courses
    output: true
  notes:
    title: Notes
    output: true
  tutorials:
    title: Tutorials
    output: true
  blog:
    title: Blog
    output: true
    permalink: /blog/:name
  fellowship_portfolio:
    title: Fellowship Portfolio
    output: true
  mentors:
    title: Mentors
    output: true
