backend:
  name: git-gateway
  branch: master # branch to update (optional; defaults to master)
  repo: https://github.com/ainc/ainc-2018

publish_mode: editorial_workflow # docs: https://www.netlifycms.org/docs/configuration-options/#publish-mode

media_folder: "images/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "_blog"
    create: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "Fellowship Portfolio"
    label: "Fellowship Portfolio"
    folder: "_fellowship_portfolio"
    create: true
    fields:
      - {label: "Company", name: "company", widget: "string"}
      - {label: "Start Date", name: "date", widget: "datetime"}
      - {label: "Logo", name: "logo", widget: "image"}
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Website", name: "website", widget: "string"}
      - {label: "Facebook", name: "facebook", widget: "string"}
      - {label: "LinkedIn", name: "linkedin", widget: "string"}
