backend:
  name: git-gateway
  branch: master # branch to update (optional; defaults to master)
  repo: https://github.com/ainc/ainc-2018

publish_mode: editorial_workflow # docs: https://www.netlifycms.org/docs/configuration-options/#publish-mode

media_folder: "images/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "_blog"
    create: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Header Image", name: "header_img", widget: "image", required: false}
      - {label: "Author Image", name: "author_img", widget: "image", required: false}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "Fellowship Portfolio"
    label: "Fellowship Portfolio"
    folder: "_fellowship_portfolio"
    create: true
    fields:
      - {label: "Company", name: "company", widget: "string"}
      - {label: "Start Date", name: "date", widget: "datetime"}
      - {label: "Logo", name: "logo", widget: "image"}
      - {label: "Website", name: "website", widget: "string", required: false}
      - {label: "Facebook", name: "facebook", widget: "string", required: false}
      - {label: "LinkedIn", name: "linkedin", widget: "string", required: false}

  - name: "Mentors"
    label: "Mentors"
    folder: "_mentors"
    create: true
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Company", name: "company", widget: "string"}
      - {label: "LinkedIn", name: "linkedin", widget: "string", required: false}

  - label: "Data"
    name: "data"
    files:
      - name: "team-alpha"
        label: "Team Alpha"
        file: "_data/team-alpha.json"
        description: "Team Alpha Members List"
        fields:
          - label: Entries
            name: Entries
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Rule, name: rule, widget: string}
              - {label: Song, name: song, widget: string}
              - {label: Person, name: person, widget: string}
              - {label: Fact, name: fact, widget: string}
              - {label: Team, name: team, widget: string}
      - name: "alumni-bootcamp"
        label: "Alumni Bootcamp"
        file: "_data/alumni-bootcamp.yml"
        description: "Bootcamp Alumni List"
        fields:
          - label: Entries
            name: Entries
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Website, name: website, widget: string}
              - {label: Github, name: github, widget: string}
              - {label: Linkedin, name: linkedin, widget: string}
              - {label: Image, name: image, widget: string}
              - {label: Position, name: position, widget: string}
              - {label: Cohort, name: cohort, widget: string}
      - name: "events"
        label: "Events"
        file: "_data/events.yml"
        description: "Current Events"
        fields:
          - label: Entries
            name: Entries
            widget: list
            fields:
              - {label: title, name: title, widget: string}
              - {label: date, name: date, widget: string}
              - {label: eventbrite_url, name: eventbrite_url, widget: string}
              - {label: feature, name: feature, widget: boolean, default: false}
              - {label: location, name: location, widget: string}
              - {label: image_url, name: image_url, widget: string}
              - {label: id, name: id, widget: string, required: false}

  - name: "Course Charts"
    label: "charts"
    folder: "_charts"
    create: true
    fields:
      - {label: "Link", name: "link", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Ages", name: "ages", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Languages", name: "languages", widget: "string"}
      - {label: "Season", name: "season", widget: "string"}
      - {label: "Time", name: "time", widget: "string"}
